### ISSUE TITLE
No main function

### ISSUE THREAD

**Issue by mlanotte1998** [chris-gomes/cs4500-a1-part2#10]
The array test has no main function

**Comment by mlanotte1998** [comment]
Also none of the created objects are deleted

**Comment by mlanotte1998** [comment]
Floats also need to be compared with some epsilon because they will likely fail comparisons of being equal even if they should be equal

**Comment by mlanotte1998** [comment]
Sorry, also on the test for the not empty append string array test, l1->get(3) should equal t2 instead of s2

**Comment by mlanotte1998** [comment]
Also the bool array get test is a t_false but the false would be at index 0 instead of 1 because of the add putting it first

**Comment by chris-gomes** [comment]
We’ll make all of the changes by tomorrow morning.

**Comment by mlanotte1998** [comment]
Okay thanks, Im going through all the tests now and so in the next hour or so I should have all of my requests in

**Comment by chris-gomes** [comment]
We also take PRs 😉

**Comment by mlanotte1998** [comment]
I can make one sometime tonight

**Comment by mlanotte1998** [comment]
I made the PR

**Comment by chris-gomes** [comment]
Thank you so much! I just approved it!

**Comment by mlanotte1998** [comment]
Hey sorry I got one more pr for a few objects that I missed initially and so now they are deleted. All the tests pass with me and there are no memory leaks so this is 99% the last issue thing you'll have to do. Thanks
