### ISSUE TITLE
tests should cast objects to String before calling equals

### ISSUE THREAD

**Issue by DNishanth** [chris-gomes/cs4500-a1-part2#14]
Since calling equals(o2) on an object will check if they are the same object, the tests should cast to String before calling equals().

Example:
`t_true(l1->get(0)->equals(t) && l1->get(1)->equals(s) && l1->size() == 2);`

**Comment by DNishanth** [comment]
Instead of casting, calling equals from the String might also work.
Example:
`t_true(t->equals(l1->get(0)) && s->equals(l1->get(1)) && l1->size() == 2);`

**Comment by anuj-modi** [comment]
Since our Equals method is virtual, this is not a problem. It should be the case that the Runtime performs Dynamic Dispatch to call the correct method.
