### ISSUE TITLE
Float, Int, Bool

### ISSUE THREAD

**Issue by mlanotte1998** [chris-gomes/cs4500-a1-part2#4]
Your tests and spec do not have a way to handle passing in bools, ints, or floats? Could make a decision on how to handle those and reflect the changes?

**Comment by DNishanth** [comment]
From Piazza, it looks like creating intArray, boolArray, etc classes is the best way to handle primitives. This design would allow for something like `int val = intArray->get(i)`

**Comment by mlanotte1998** [comment]
But there are no tests for ints and bools and floats so there is no current way with the spec to go about it. My understanding from piazza is that the tests dictate the implementation so if they add IntArrays and classes like that then that's what needs to be implemented. Right now I don't think there is enough in the tests to show how this should be done.

**Comment by DNishanth** [comment]
I agree, my comment was just a suggestion for how they could change their API and tests.

**Comment by mlanotte1998** [comment]
Oh okay, my bad. Glad you agree

**Comment by chris-gomes** [comment]
We were originally planning on having the implementation be wrapper classes for primitive types. We were waiting to see how the conversations on Piazza developed and given note @397 we are going to include separate arrays for each of the primitive types. They should be up in the next few hours. Apologies for the confusion.

**Comment by chris-gomes** [comment]
It's up guys! I didn't have the array classes extend the original Array, because all of their method signatures would be different anyway. All of the array classes are now in array.h and there should be tests for all of them.

**Comment by DNishanth** [comment]
Thanks! Do you think we also need a StringArray? The base array class can contain strings but it can also contain other Objects at the same time.

**Comment by chris-gomes** [comment]
I think it's better to keep as is. Allows more flexibility to be able to except other types of objects in the future (not saying we'll need to do that but that it is good to allow designs to be reusable whenever possible, instead of continuing to make a new array class for every new thing we want to store)
