### ISSUE TITLE
array index_of() return type conflict

### ISSUE THREAD

**Issue by DNishanth** [chris-gomes/cs4500-a1-part2#5]
The description of index_of() states that -1 should be returned if the given element is not in the array. This conflicts with the return type since -1 is not a valid size_t. Can you change the return value in the description to >size() instead of -1?

**Comment by anuj-modi** [comment]
We forgot to update the tests. @chris-gomes  please take care of this

**Comment by chris-gomes** [comment]
Corrected this in most recent commit
