### ISSUE TITLE
remove return

### ISSUE THREAD

**Issue by mlanotte1998** [chris-gomes/cs4500-a1-part2#9]
Hey guys, I noticed with the remove function for the IntArray says to return a null pointer but the return for the function is an int. Im assuming that the BoolArray and FloatArray have similar returns, I'm not sure what you think should be the returns instead

**Comment by chris-gomes** [comment]
you can have it return -1, -1.0, and false. You're also welcome to make it return an assertion error instead. apologies for the confusion. It's old wording. It's just comments so you can just update it on your end.
